/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IMOLOCH } from "../IMOLOCH";

export class IMOLOCH__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMOLOCH {
    return new Contract(address, _abi, signerOrProvider) as IMOLOCH;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
    ],
    name: "getProposalFlags",
    outputs: [
      {
        internalType: "bool[6]",
        name: "",
        type: "bool[6]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "applicant",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "sharesRequested",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "lootRequested",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "tributeOffered",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "tributeToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "paymentRequested",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "paymentToken",
        type: "address",
      },
      {
        internalType: "string",
        name: "details",
        type: "string",
      },
    ],
    name: "submitProposal",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdrawBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
