/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface SushiNomikaiInterface extends ethers.utils.Interface {
  functions: {
    "ESCROW()": FunctionFragment;
    "GUILD()": FunctionFragment;
    "TOTAL()": FunctionFragment;
    "approvedTokens(uint256)": FunctionFragment;
    "canRagequit(uint256)": FunctionFragment;
    "cancelProposal(uint256)": FunctionFragment;
    "collectTokens(address)": FunctionFragment;
    "dilutionBound()": FunctionFragment;
    "getCurrentPeriod()": FunctionFragment;
    "getMemberProposalVote(address,uint256)": FunctionFragment;
    "getProposalFlags(uint256)": FunctionFragment;
    "getProposalQueueLength()": FunctionFragment;
    "getTokenCount()": FunctionFragment;
    "getUserTokenBalance(address,address)": FunctionFragment;
    "gracePeriodLength()": FunctionFragment;
    "hasVotingPeriodExpired(uint256)": FunctionFragment;
    "internalTransfer(address,address,uint256)": FunctionFragment;
    "makeSushiDeposit(uint256)": FunctionFragment;
    "makeXSushiDeposit(uint256)": FunctionFragment;
    "memberAddressByDelegateKey(address)": FunctionFragment;
    "members(address)": FunctionFragment;
    "periodDuration()": FunctionFragment;
    "processGuildKickProposal(uint256)": FunctionFragment;
    "processProposal(uint256)": FunctionFragment;
    "processWhitelistProposal(uint256)": FunctionFragment;
    "processingReward()": FunctionFragment;
    "proposalCount()": FunctionFragment;
    "proposalDeposit()": FunctionFragment;
    "proposalQueue(uint256)": FunctionFragment;
    "proposals(uint256)": FunctionFragment;
    "proposedToKick(address)": FunctionFragment;
    "proposedToWhitelist(address)": FunctionFragment;
    "ragekick(address)": FunctionFragment;
    "ragequit(uint256,uint256)": FunctionFragment;
    "sponsorProposal(uint256)": FunctionFragment;
    "submitGuildKickProposal(address,string)": FunctionFragment;
    "submitProposal(address,uint256,uint256,uint256,address,uint256,address,string)": FunctionFragment;
    "submitVote(uint256,uint8)": FunctionFragment;
    "submitWhitelistProposal(address,string)": FunctionFragment;
    "sushiMinion()": FunctionFragment;
    "tokenWhitelist(address)": FunctionFragment;
    "totalGuildBankTokens()": FunctionFragment;
    "totalLoot()": FunctionFragment;
    "totalShares()": FunctionFragment;
    "updateDelegateKey(address)": FunctionFragment;
    "userTokenBalances(address,address)": FunctionFragment;
    "votingPeriodLength()": FunctionFragment;
    "withdrawBalance(address,uint256)": FunctionFragment;
    "withdrawBalances(address[],uint256[],bool)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "ESCROW", values?: undefined): string;
  encodeFunctionData(functionFragment: "GUILD", values?: undefined): string;
  encodeFunctionData(functionFragment: "TOTAL", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "approvedTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canRagequit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectTokens",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "dilutionBound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMemberProposalVote",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalFlags",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalQueueLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTokenBalance",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "gracePeriodLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasVotingPeriodExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "internalTransfer",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "makeSushiDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "makeXSushiDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "memberAddressByDelegateKey",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "members", values: [string]): string;
  encodeFunctionData(
    functionFragment: "periodDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processGuildKickProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processWhitelistProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "processingReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalQueue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposedToKick",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "proposedToWhitelist",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "ragekick", values: [string]): string;
  encodeFunctionData(
    functionFragment: "ragequit",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sponsorProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitGuildKickProposal",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProposal",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitVote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWhitelistProposal",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sushiMinion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenWhitelist",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalGuildBankTokens",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "totalLoot", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateDelegateKey",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "userTokenBalances",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "votingPeriodLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBalance",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBalances",
    values: [string[], BigNumberish[], boolean]
  ): string;

  decodeFunctionResult(functionFragment: "ESCROW", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "GUILD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TOTAL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approvedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canRagequit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dilutionBound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemberProposalVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalFlags",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalQueueLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gracePeriodLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasVotingPeriodExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "internalTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeSushiDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeXSushiDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memberAddressByDelegateKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "members", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "periodDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processGuildKickProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processWhitelistProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalQueue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposedToKick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposedToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ragekick", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ragequit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sponsorProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitGuildKickProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitWhitelistProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sushiMinion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalGuildBankTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalLoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDelegateKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTokenBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingPeriodLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBalances",
    data: BytesLike
  ): Result;

  events: {
    "CancelProposal(uint256,address)": EventFragment;
    "InternalTransfer(address,address,address,uint256)": EventFragment;
    "MakeDeposit(address,uint256,uint256)": EventFragment;
    "ProcessGuildKickProposal(uint256,uint256,bool)": EventFragment;
    "ProcessProposal(uint256,uint256,bool)": EventFragment;
    "ProcessWhitelistProposal(uint256,uint256,bool)": EventFragment;
    "Ragequit(address,uint256,uint256)": EventFragment;
    "SponsorProposal(address,address,uint256,uint256,uint256)": EventFragment;
    "SubmitProposal(address,uint256,uint256,uint256,address,uint256,address,string,bool[6],uint256,address,address)": EventFragment;
    "SubmitVote(uint256,uint256,address,address,uint8)": EventFragment;
    "SummonComplete(address,address[],uint256,uint256,uint256,uint256,uint256,uint256,uint256)": EventFragment;
    "TokensCollected(address,uint256)": EventFragment;
    "UpdateDelegateKey(address,address)": EventFragment;
    "Withdraw(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CancelProposal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InternalTransfer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MakeDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProcessGuildKickProposal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProcessProposal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProcessWhitelistProposal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Ragequit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SponsorProposal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SubmitProposal"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SubmitVote"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SummonComplete"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensCollected"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateDelegateKey"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export class SushiNomikai extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SushiNomikaiInterface;

  functions: {
    ESCROW(overrides?: CallOverrides): Promise<[string]>;

    "ESCROW()"(overrides?: CallOverrides): Promise<[string]>;

    GUILD(overrides?: CallOverrides): Promise<[string]>;

    "GUILD()"(overrides?: CallOverrides): Promise<[string]>;

    TOTAL(overrides?: CallOverrides): Promise<[string]>;

    "TOTAL()"(overrides?: CallOverrides): Promise<[string]>;

    approvedTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "approvedTokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    canRagequit(
      highestIndexYesVote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "canRagequit(uint256)"(
      highestIndexYesVote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    cancelProposal(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "cancelProposal(uint256)"(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    collectTokens(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "collectTokens(address)"(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    dilutionBound(overrides?: CallOverrides): Promise<[BigNumber]>;

    "dilutionBound()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCurrentPeriod(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getCurrentPeriod()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMemberProposalVote(
      memberAddress: string,
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    "getMemberProposalVote(address,uint256)"(
      memberAddress: string,
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    getProposalFlags(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[[boolean, boolean, boolean, boolean, boolean, boolean]]>;

    "getProposalFlags(uint256)"(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[[boolean, boolean, boolean, boolean, boolean, boolean]]>;

    getProposalQueueLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getProposalQueueLength()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTokenCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "getTokenCount()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getUserTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "getUserTokenBalance(address,address)"(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    gracePeriodLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    "gracePeriodLength()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    hasVotingPeriodExpired(
      startingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "hasVotingPeriodExpired(uint256)"(
      startingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    internalTransfer(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "internalTransfer(address,address,uint256)"(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    makeSushiDeposit(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "makeSushiDeposit(uint256)"(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    makeXSushiDeposit(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "makeXSushiDeposit(uint256)"(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    memberAddressByDelegateKey(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "memberAddressByDelegateKey(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    members(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, boolean, BigNumber, BigNumber] & {
        delegateKey: string;
        shares: BigNumber;
        loot: BigNumber;
        exists: boolean;
        highestIndexYesVote: BigNumber;
        jailed: BigNumber;
      }
    >;

    "members(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, boolean, BigNumber, BigNumber] & {
        delegateKey: string;
        shares: BigNumber;
        loot: BigNumber;
        exists: boolean;
        highestIndexYesVote: BigNumber;
        jailed: BigNumber;
      }
    >;

    periodDuration(overrides?: CallOverrides): Promise<[BigNumber]>;

    "periodDuration()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    processGuildKickProposal(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "processGuildKickProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    processProposal(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "processProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    processWhitelistProposal(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "processWhitelistProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    processingReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    "processingReward()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    proposalCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "proposalCount()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    proposalDeposit(overrides?: CallOverrides): Promise<[BigNumber]>;

    "proposalDeposit()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    proposalQueue(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "proposalQueue(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ] & {
        applicant: string;
        proposer: string;
        sponsor: string;
        sharesRequested: BigNumber;
        lootRequested: BigNumber;
        tributeOffered: BigNumber;
        tributeToken: string;
        paymentRequested: BigNumber;
        paymentToken: string;
        startingPeriod: BigNumber;
        yesVotes: BigNumber;
        noVotes: BigNumber;
        details: string;
        maxTotalSharesAndLootAtYesVote: BigNumber;
      }
    >;

    "proposals(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ] & {
        applicant: string;
        proposer: string;
        sponsor: string;
        sharesRequested: BigNumber;
        lootRequested: BigNumber;
        tributeOffered: BigNumber;
        tributeToken: string;
        paymentRequested: BigNumber;
        paymentToken: string;
        startingPeriod: BigNumber;
        yesVotes: BigNumber;
        noVotes: BigNumber;
        details: string;
        maxTotalSharesAndLootAtYesVote: BigNumber;
      }
    >;

    proposedToKick(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "proposedToKick(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    proposedToWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "proposedToWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    ragekick(
      memberToKick: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "ragekick(address)"(
      memberToKick: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ragequit(
      sharesToBurn: BigNumberish,
      lootToBurn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "ragequit(uint256,uint256)"(
      sharesToBurn: BigNumberish,
      lootToBurn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sponsorProposal(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "sponsorProposal(uint256)"(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    submitGuildKickProposal(
      memberToKick: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "submitGuildKickProposal(address,string)"(
      memberToKick: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    submitProposal(
      applicant: string,
      sharesRequested: BigNumberish,
      lootRequested: BigNumberish,
      tributeOffered: BigNumberish,
      tributeToken: string,
      paymentRequested: BigNumberish,
      paymentToken: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "submitProposal(address,uint256,uint256,uint256,address,uint256,address,string)"(
      applicant: string,
      sharesRequested: BigNumberish,
      lootRequested: BigNumberish,
      tributeOffered: BigNumberish,
      tributeToken: string,
      paymentRequested: BigNumberish,
      paymentToken: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    submitVote(
      proposalIndex: BigNumberish,
      uintVote: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "submitVote(uint256,uint8)"(
      proposalIndex: BigNumberish,
      uintVote: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    submitWhitelistProposal(
      tokenToWhitelist: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "submitWhitelistProposal(address,string)"(
      tokenToWhitelist: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sushiMinion(overrides?: CallOverrides): Promise<[string]>;

    "sushiMinion()"(overrides?: CallOverrides): Promise<[string]>;

    tokenWhitelist(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "tokenWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    totalGuildBankTokens(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalGuildBankTokens()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalLoot(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalLoot()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    totalShares(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totalShares()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    updateDelegateKey(
      newDelegateKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "updateDelegateKey(address)"(
      newDelegateKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userTokenBalances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "userTokenBalances(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    votingPeriodLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    "votingPeriodLength()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    withdrawBalance(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "withdrawBalance(address,uint256)"(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdrawBalances(
      tokens: string[],
      amounts: BigNumberish[],
      max: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "withdrawBalances(address[],uint256[],bool)"(
      tokens: string[],
      amounts: BigNumberish[],
      max: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  ESCROW(overrides?: CallOverrides): Promise<string>;

  "ESCROW()"(overrides?: CallOverrides): Promise<string>;

  GUILD(overrides?: CallOverrides): Promise<string>;

  "GUILD()"(overrides?: CallOverrides): Promise<string>;

  TOTAL(overrides?: CallOverrides): Promise<string>;

  "TOTAL()"(overrides?: CallOverrides): Promise<string>;

  approvedTokens(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "approvedTokens(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  canRagequit(
    highestIndexYesVote: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "canRagequit(uint256)"(
    highestIndexYesVote: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  cancelProposal(
    proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "cancelProposal(uint256)"(
    proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  collectTokens(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "collectTokens(address)"(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  dilutionBound(overrides?: CallOverrides): Promise<BigNumber>;

  "dilutionBound()"(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentPeriod(overrides?: CallOverrides): Promise<BigNumber>;

  "getCurrentPeriod()"(overrides?: CallOverrides): Promise<BigNumber>;

  getMemberProposalVote(
    memberAddress: string,
    proposalIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  "getMemberProposalVote(address,uint256)"(
    memberAddress: string,
    proposalIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  getProposalFlags(
    proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[boolean, boolean, boolean, boolean, boolean, boolean]>;

  "getProposalFlags(uint256)"(
    proposalId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[boolean, boolean, boolean, boolean, boolean, boolean]>;

  getProposalQueueLength(overrides?: CallOverrides): Promise<BigNumber>;

  "getProposalQueueLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  getTokenCount(overrides?: CallOverrides): Promise<BigNumber>;

  "getTokenCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  getUserTokenBalance(
    user: string,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getUserTokenBalance(address,address)"(
    user: string,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  gracePeriodLength(overrides?: CallOverrides): Promise<BigNumber>;

  "gracePeriodLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  hasVotingPeriodExpired(
    startingPeriod: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "hasVotingPeriodExpired(uint256)"(
    startingPeriod: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  internalTransfer(
    to: string,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "internalTransfer(address,address,uint256)"(
    to: string,
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  makeSushiDeposit(
    tributeOffered: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "makeSushiDeposit(uint256)"(
    tributeOffered: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  makeXSushiDeposit(
    tributeOffered: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "makeXSushiDeposit(uint256)"(
    tributeOffered: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  memberAddressByDelegateKey(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "memberAddressByDelegateKey(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  members(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, boolean, BigNumber, BigNumber] & {
      delegateKey: string;
      shares: BigNumber;
      loot: BigNumber;
      exists: boolean;
      highestIndexYesVote: BigNumber;
      jailed: BigNumber;
    }
  >;

  "members(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, boolean, BigNumber, BigNumber] & {
      delegateKey: string;
      shares: BigNumber;
      loot: BigNumber;
      exists: boolean;
      highestIndexYesVote: BigNumber;
      jailed: BigNumber;
    }
  >;

  periodDuration(overrides?: CallOverrides): Promise<BigNumber>;

  "periodDuration()"(overrides?: CallOverrides): Promise<BigNumber>;

  processGuildKickProposal(
    proposalIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "processGuildKickProposal(uint256)"(
    proposalIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  processProposal(
    proposalIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "processProposal(uint256)"(
    proposalIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  processWhitelistProposal(
    proposalIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "processWhitelistProposal(uint256)"(
    proposalIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  processingReward(overrides?: CallOverrides): Promise<BigNumber>;

  "processingReward()"(overrides?: CallOverrides): Promise<BigNumber>;

  proposalCount(overrides?: CallOverrides): Promise<BigNumber>;

  "proposalCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  proposalDeposit(overrides?: CallOverrides): Promise<BigNumber>;

  "proposalDeposit()"(overrides?: CallOverrides): Promise<BigNumber>;

  proposalQueue(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "proposalQueue(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  proposals(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      BigNumber
    ] & {
      applicant: string;
      proposer: string;
      sponsor: string;
      sharesRequested: BigNumber;
      lootRequested: BigNumber;
      tributeOffered: BigNumber;
      tributeToken: string;
      paymentRequested: BigNumber;
      paymentToken: string;
      startingPeriod: BigNumber;
      yesVotes: BigNumber;
      noVotes: BigNumber;
      details: string;
      maxTotalSharesAndLootAtYesVote: BigNumber;
    }
  >;

  "proposals(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      BigNumber,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      BigNumber
    ] & {
      applicant: string;
      proposer: string;
      sponsor: string;
      sharesRequested: BigNumber;
      lootRequested: BigNumber;
      tributeOffered: BigNumber;
      tributeToken: string;
      paymentRequested: BigNumber;
      paymentToken: string;
      startingPeriod: BigNumber;
      yesVotes: BigNumber;
      noVotes: BigNumber;
      details: string;
      maxTotalSharesAndLootAtYesVote: BigNumber;
    }
  >;

  proposedToKick(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "proposedToKick(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  proposedToWhitelist(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "proposedToWhitelist(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  ragekick(
    memberToKick: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "ragekick(address)"(
    memberToKick: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ragequit(
    sharesToBurn: BigNumberish,
    lootToBurn: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "ragequit(uint256,uint256)"(
    sharesToBurn: BigNumberish,
    lootToBurn: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sponsorProposal(
    proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "sponsorProposal(uint256)"(
    proposalId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  submitGuildKickProposal(
    memberToKick: string,
    details: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "submitGuildKickProposal(address,string)"(
    memberToKick: string,
    details: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  submitProposal(
    applicant: string,
    sharesRequested: BigNumberish,
    lootRequested: BigNumberish,
    tributeOffered: BigNumberish,
    tributeToken: string,
    paymentRequested: BigNumberish,
    paymentToken: string,
    details: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "submitProposal(address,uint256,uint256,uint256,address,uint256,address,string)"(
    applicant: string,
    sharesRequested: BigNumberish,
    lootRequested: BigNumberish,
    tributeOffered: BigNumberish,
    tributeToken: string,
    paymentRequested: BigNumberish,
    paymentToken: string,
    details: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  submitVote(
    proposalIndex: BigNumberish,
    uintVote: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "submitVote(uint256,uint8)"(
    proposalIndex: BigNumberish,
    uintVote: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  submitWhitelistProposal(
    tokenToWhitelist: string,
    details: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "submitWhitelistProposal(address,string)"(
    tokenToWhitelist: string,
    details: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sushiMinion(overrides?: CallOverrides): Promise<string>;

  "sushiMinion()"(overrides?: CallOverrides): Promise<string>;

  tokenWhitelist(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "tokenWhitelist(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  totalGuildBankTokens(overrides?: CallOverrides): Promise<BigNumber>;

  "totalGuildBankTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

  totalLoot(overrides?: CallOverrides): Promise<BigNumber>;

  "totalLoot()"(overrides?: CallOverrides): Promise<BigNumber>;

  totalShares(overrides?: CallOverrides): Promise<BigNumber>;

  "totalShares()"(overrides?: CallOverrides): Promise<BigNumber>;

  updateDelegateKey(
    newDelegateKey: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "updateDelegateKey(address)"(
    newDelegateKey: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userTokenBalances(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "userTokenBalances(address,address)"(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  votingPeriodLength(overrides?: CallOverrides): Promise<BigNumber>;

  "votingPeriodLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  withdrawBalance(
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "withdrawBalance(address,uint256)"(
    token: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdrawBalances(
    tokens: string[],
    amounts: BigNumberish[],
    max: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "withdrawBalances(address[],uint256[],bool)"(
    tokens: string[],
    amounts: BigNumberish[],
    max: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    ESCROW(overrides?: CallOverrides): Promise<string>;

    "ESCROW()"(overrides?: CallOverrides): Promise<string>;

    GUILD(overrides?: CallOverrides): Promise<string>;

    "GUILD()"(overrides?: CallOverrides): Promise<string>;

    TOTAL(overrides?: CallOverrides): Promise<string>;

    "TOTAL()"(overrides?: CallOverrides): Promise<string>;

    approvedTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "approvedTokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    canRagequit(
      highestIndexYesVote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "canRagequit(uint256)"(
      highestIndexYesVote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    cancelProposal(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "cancelProposal(uint256)"(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    collectTokens(token: string, overrides?: CallOverrides): Promise<void>;

    "collectTokens(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    dilutionBound(overrides?: CallOverrides): Promise<BigNumber>;

    "dilutionBound()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    "getCurrentPeriod()"(overrides?: CallOverrides): Promise<BigNumber>;

    getMemberProposalVote(
      memberAddress: string,
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    "getMemberProposalVote(address,uint256)"(
      memberAddress: string,
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;

    getProposalFlags(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, boolean, boolean, boolean, boolean, boolean]>;

    "getProposalFlags(uint256)"(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean, boolean, boolean, boolean, boolean, boolean]>;

    getProposalQueueLength(overrides?: CallOverrides): Promise<BigNumber>;

    "getProposalQueueLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenCount(overrides?: CallOverrides): Promise<BigNumber>;

    "getTokenCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    getUserTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getUserTokenBalance(address,address)"(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gracePeriodLength(overrides?: CallOverrides): Promise<BigNumber>;

    "gracePeriodLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    hasVotingPeriodExpired(
      startingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasVotingPeriodExpired(uint256)"(
      startingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    internalTransfer(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "internalTransfer(address,address,uint256)"(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    makeSushiDeposit(
      tributeOffered: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "makeSushiDeposit(uint256)"(
      tributeOffered: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    makeXSushiDeposit(
      tributeOffered: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "makeXSushiDeposit(uint256)"(
      tributeOffered: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    memberAddressByDelegateKey(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "memberAddressByDelegateKey(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    members(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, boolean, BigNumber, BigNumber] & {
        delegateKey: string;
        shares: BigNumber;
        loot: BigNumber;
        exists: boolean;
        highestIndexYesVote: BigNumber;
        jailed: BigNumber;
      }
    >;

    "members(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, boolean, BigNumber, BigNumber] & {
        delegateKey: string;
        shares: BigNumber;
        loot: BigNumber;
        exists: boolean;
        highestIndexYesVote: BigNumber;
        jailed: BigNumber;
      }
    >;

    periodDuration(overrides?: CallOverrides): Promise<BigNumber>;

    "periodDuration()"(overrides?: CallOverrides): Promise<BigNumber>;

    processGuildKickProposal(
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "processGuildKickProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    processProposal(
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "processProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    processWhitelistProposal(
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "processWhitelistProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    processingReward(overrides?: CallOverrides): Promise<BigNumber>;

    "processingReward()"(overrides?: CallOverrides): Promise<BigNumber>;

    proposalCount(overrides?: CallOverrides): Promise<BigNumber>;

    "proposalCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    proposalDeposit(overrides?: CallOverrides): Promise<BigNumber>;

    "proposalDeposit()"(overrides?: CallOverrides): Promise<BigNumber>;

    proposalQueue(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proposalQueue(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ] & {
        applicant: string;
        proposer: string;
        sponsor: string;
        sharesRequested: BigNumber;
        lootRequested: BigNumber;
        tributeOffered: BigNumber;
        tributeToken: string;
        paymentRequested: BigNumber;
        paymentToken: string;
        startingPeriod: BigNumber;
        yesVotes: BigNumber;
        noVotes: BigNumber;
        details: string;
        maxTotalSharesAndLootAtYesVote: BigNumber;
      }
    >;

    "proposals(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber
      ] & {
        applicant: string;
        proposer: string;
        sponsor: string;
        sharesRequested: BigNumber;
        lootRequested: BigNumber;
        tributeOffered: BigNumber;
        tributeToken: string;
        paymentRequested: BigNumber;
        paymentToken: string;
        startingPeriod: BigNumber;
        yesVotes: BigNumber;
        noVotes: BigNumber;
        details: string;
        maxTotalSharesAndLootAtYesVote: BigNumber;
      }
    >;

    proposedToKick(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "proposedToKick(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    proposedToWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "proposedToWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    ragekick(memberToKick: string, overrides?: CallOverrides): Promise<void>;

    "ragekick(address)"(
      memberToKick: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ragequit(
      sharesToBurn: BigNumberish,
      lootToBurn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "ragequit(uint256,uint256)"(
      sharesToBurn: BigNumberish,
      lootToBurn: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    sponsorProposal(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "sponsorProposal(uint256)"(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    submitGuildKickProposal(
      memberToKick: string,
      details: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "submitGuildKickProposal(address,string)"(
      memberToKick: string,
      details: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    submitProposal(
      applicant: string,
      sharesRequested: BigNumberish,
      lootRequested: BigNumberish,
      tributeOffered: BigNumberish,
      tributeToken: string,
      paymentRequested: BigNumberish,
      paymentToken: string,
      details: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "submitProposal(address,uint256,uint256,uint256,address,uint256,address,string)"(
      applicant: string,
      sharesRequested: BigNumberish,
      lootRequested: BigNumberish,
      tributeOffered: BigNumberish,
      tributeToken: string,
      paymentRequested: BigNumberish,
      paymentToken: string,
      details: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    submitVote(
      proposalIndex: BigNumberish,
      uintVote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "submitVote(uint256,uint8)"(
      proposalIndex: BigNumberish,
      uintVote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    submitWhitelistProposal(
      tokenToWhitelist: string,
      details: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "submitWhitelistProposal(address,string)"(
      tokenToWhitelist: string,
      details: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sushiMinion(overrides?: CallOverrides): Promise<string>;

    "sushiMinion()"(overrides?: CallOverrides): Promise<string>;

    tokenWhitelist(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "tokenWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    totalGuildBankTokens(overrides?: CallOverrides): Promise<BigNumber>;

    "totalGuildBankTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalLoot(overrides?: CallOverrides): Promise<BigNumber>;

    "totalLoot()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;

    "totalShares()"(overrides?: CallOverrides): Promise<BigNumber>;

    updateDelegateKey(
      newDelegateKey: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateDelegateKey(address)"(
      newDelegateKey: string,
      overrides?: CallOverrides
    ): Promise<void>;

    userTokenBalances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userTokenBalances(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votingPeriodLength(overrides?: CallOverrides): Promise<BigNumber>;

    "votingPeriodLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawBalance(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawBalance(address,uint256)"(
      token: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawBalances(
      tokens: string[],
      amounts: BigNumberish[],
      max: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawBalances(address[],uint256[],bool)"(
      tokens: string[],
      amounts: BigNumberish[],
      max: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    CancelProposal(
      proposalId: BigNumberish | null,
      applicantAddress: null
    ): TypedEventFilter<
      [BigNumber, string],
      { proposalId: BigNumber; applicantAddress: string }
    >;

    InternalTransfer(
      from: string | null,
      to: string | null,
      token: null,
      amount: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      { from: string; to: string; token: string; amount: BigNumber }
    >;

    MakeDeposit(
      memberAddress: string | null,
      tributeOffered: null,
      shares: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { memberAddress: string; tributeOffered: BigNumber; shares: BigNumber }
    >;

    ProcessGuildKickProposal(
      proposalIndex: BigNumberish | null,
      proposalId: BigNumberish | null,
      didPass: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, boolean],
      { proposalIndex: BigNumber; proposalId: BigNumber; didPass: boolean }
    >;

    ProcessProposal(
      proposalIndex: BigNumberish | null,
      proposalId: BigNumberish | null,
      didPass: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, boolean],
      { proposalIndex: BigNumber; proposalId: BigNumber; didPass: boolean }
    >;

    ProcessWhitelistProposal(
      proposalIndex: BigNumberish | null,
      proposalId: BigNumberish | null,
      didPass: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, boolean],
      { proposalIndex: BigNumber; proposalId: BigNumber; didPass: boolean }
    >;

    Ragequit(
      memberAddress: string | null,
      sharesToBurn: null,
      lootToBurn: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { memberAddress: string; sharesToBurn: BigNumber; lootToBurn: BigNumber }
    >;

    SponsorProposal(
      delegateKey: string | null,
      memberAddress: string | null,
      proposalId: null,
      proposalIndex: null,
      startingPeriod: null
    ): TypedEventFilter<
      [string, string, BigNumber, BigNumber, BigNumber],
      {
        delegateKey: string;
        memberAddress: string;
        proposalId: BigNumber;
        proposalIndex: BigNumber;
        startingPeriod: BigNumber;
      }
    >;

    SubmitProposal(
      applicant: string | null,
      sharesRequested: null,
      lootRequested: null,
      tributeOffered: null,
      tributeToken: null,
      paymentRequested: null,
      paymentToken: null,
      details: null,
      flags: null,
      proposalId: null,
      delegateKey: string | null,
      memberAddress: string | null
    ): TypedEventFilter<
      [
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        BigNumber,
        string,
        string,
        [boolean, boolean, boolean, boolean, boolean, boolean],
        BigNumber,
        string,
        string
      ],
      {
        applicant: string;
        sharesRequested: BigNumber;
        lootRequested: BigNumber;
        tributeOffered: BigNumber;
        tributeToken: string;
        paymentRequested: BigNumber;
        paymentToken: string;
        details: string;
        flags: [boolean, boolean, boolean, boolean, boolean, boolean];
        proposalId: BigNumber;
        delegateKey: string;
        memberAddress: string;
      }
    >;

    SubmitVote(
      proposalId: null,
      proposalIndex: BigNumberish | null,
      delegateKey: string | null,
      memberAddress: string | null,
      uintVote: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, string, number],
      {
        proposalId: BigNumber;
        proposalIndex: BigNumber;
        delegateKey: string;
        memberAddress: string;
        uintVote: number;
      }
    >;

    SummonComplete(
      summoner: string | null,
      tokens: null,
      summoningTime: null,
      periodDuration: null,
      votingPeriodLength: null,
      gracePeriodLength: null,
      proposalDeposit: null,
      dilutionBound: null,
      processingReward: null
    ): TypedEventFilter<
      [
        string,
        string[],
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ],
      {
        summoner: string;
        tokens: string[];
        summoningTime: BigNumber;
        periodDuration: BigNumber;
        votingPeriodLength: BigNumber;
        gracePeriodLength: BigNumber;
        proposalDeposit: BigNumber;
        dilutionBound: BigNumber;
        processingReward: BigNumber;
      }
    >;

    TokensCollected(
      token: string | null,
      amountToCollect: null
    ): TypedEventFilter<
      [string, BigNumber],
      { token: string; amountToCollect: BigNumber }
    >;

    UpdateDelegateKey(
      memberAddress: string | null,
      newDelegateKey: null
    ): TypedEventFilter<
      [string, string],
      { memberAddress: string; newDelegateKey: string }
    >;

    Withdraw(
      memberAddress: string | null,
      token: null,
      amount: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { memberAddress: string; token: string; amount: BigNumber }
    >;
  };

  estimateGas: {
    ESCROW(overrides?: CallOverrides): Promise<BigNumber>;

    "ESCROW()"(overrides?: CallOverrides): Promise<BigNumber>;

    GUILD(overrides?: CallOverrides): Promise<BigNumber>;

    "GUILD()"(overrides?: CallOverrides): Promise<BigNumber>;

    TOTAL(overrides?: CallOverrides): Promise<BigNumber>;

    "TOTAL()"(overrides?: CallOverrides): Promise<BigNumber>;

    approvedTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "approvedTokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    canRagequit(
      highestIndexYesVote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "canRagequit(uint256)"(
      highestIndexYesVote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    cancelProposal(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "cancelProposal(uint256)"(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    collectTokens(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "collectTokens(address)"(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    dilutionBound(overrides?: CallOverrides): Promise<BigNumber>;

    "dilutionBound()"(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentPeriod(overrides?: CallOverrides): Promise<BigNumber>;

    "getCurrentPeriod()"(overrides?: CallOverrides): Promise<BigNumber>;

    getMemberProposalVote(
      memberAddress: string,
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getMemberProposalVote(address,uint256)"(
      memberAddress: string,
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposalFlags(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getProposalFlags(uint256)"(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProposalQueueLength(overrides?: CallOverrides): Promise<BigNumber>;

    "getProposalQueueLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTokenCount(overrides?: CallOverrides): Promise<BigNumber>;

    "getTokenCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    getUserTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getUserTokenBalance(address,address)"(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gracePeriodLength(overrides?: CallOverrides): Promise<BigNumber>;

    "gracePeriodLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    hasVotingPeriodExpired(
      startingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hasVotingPeriodExpired(uint256)"(
      startingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    internalTransfer(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "internalTransfer(address,address,uint256)"(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    makeSushiDeposit(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "makeSushiDeposit(uint256)"(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    makeXSushiDeposit(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "makeXSushiDeposit(uint256)"(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    memberAddressByDelegateKey(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "memberAddressByDelegateKey(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    members(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "members(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    periodDuration(overrides?: CallOverrides): Promise<BigNumber>;

    "periodDuration()"(overrides?: CallOverrides): Promise<BigNumber>;

    processGuildKickProposal(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "processGuildKickProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    processProposal(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "processProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    processWhitelistProposal(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "processWhitelistProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    processingReward(overrides?: CallOverrides): Promise<BigNumber>;

    "processingReward()"(overrides?: CallOverrides): Promise<BigNumber>;

    proposalCount(overrides?: CallOverrides): Promise<BigNumber>;

    "proposalCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    proposalDeposit(overrides?: CallOverrides): Promise<BigNumber>;

    "proposalDeposit()"(overrides?: CallOverrides): Promise<BigNumber>;

    proposalQueue(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proposalQueue(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proposals(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposedToKick(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "proposedToKick(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proposedToWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proposedToWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    ragekick(
      memberToKick: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "ragekick(address)"(
      memberToKick: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ragequit(
      sharesToBurn: BigNumberish,
      lootToBurn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "ragequit(uint256,uint256)"(
      sharesToBurn: BigNumberish,
      lootToBurn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sponsorProposal(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "sponsorProposal(uint256)"(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    submitGuildKickProposal(
      memberToKick: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "submitGuildKickProposal(address,string)"(
      memberToKick: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    submitProposal(
      applicant: string,
      sharesRequested: BigNumberish,
      lootRequested: BigNumberish,
      tributeOffered: BigNumberish,
      tributeToken: string,
      paymentRequested: BigNumberish,
      paymentToken: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "submitProposal(address,uint256,uint256,uint256,address,uint256,address,string)"(
      applicant: string,
      sharesRequested: BigNumberish,
      lootRequested: BigNumberish,
      tributeOffered: BigNumberish,
      tributeToken: string,
      paymentRequested: BigNumberish,
      paymentToken: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    submitVote(
      proposalIndex: BigNumberish,
      uintVote: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "submitVote(uint256,uint8)"(
      proposalIndex: BigNumberish,
      uintVote: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    submitWhitelistProposal(
      tokenToWhitelist: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "submitWhitelistProposal(address,string)"(
      tokenToWhitelist: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sushiMinion(overrides?: CallOverrides): Promise<BigNumber>;

    "sushiMinion()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokenWhitelist(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "tokenWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalGuildBankTokens(overrides?: CallOverrides): Promise<BigNumber>;

    "totalGuildBankTokens()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalLoot(overrides?: CallOverrides): Promise<BigNumber>;

    "totalLoot()"(overrides?: CallOverrides): Promise<BigNumber>;

    totalShares(overrides?: CallOverrides): Promise<BigNumber>;

    "totalShares()"(overrides?: CallOverrides): Promise<BigNumber>;

    updateDelegateKey(
      newDelegateKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "updateDelegateKey(address)"(
      newDelegateKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userTokenBalances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "userTokenBalances(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votingPeriodLength(overrides?: CallOverrides): Promise<BigNumber>;

    "votingPeriodLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawBalance(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "withdrawBalance(address,uint256)"(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdrawBalances(
      tokens: string[],
      amounts: BigNumberish[],
      max: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "withdrawBalances(address[],uint256[],bool)"(
      tokens: string[],
      amounts: BigNumberish[],
      max: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    ESCROW(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "ESCROW()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    GUILD(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "GUILD()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TOTAL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "TOTAL()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    approvedTokens(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "approvedTokens(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    canRagequit(
      highestIndexYesVote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "canRagequit(uint256)"(
      highestIndexYesVote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    cancelProposal(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "cancelProposal(uint256)"(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    collectTokens(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "collectTokens(address)"(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    dilutionBound(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "dilutionBound()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurrentPeriod(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getCurrentPeriod()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMemberProposalVote(
      memberAddress: string,
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getMemberProposalVote(address,uint256)"(
      memberAddress: string,
      proposalIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProposalFlags(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getProposalFlags(uint256)"(
      proposalId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProposalQueueLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getProposalQueueLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getTokenCount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUserTokenBalance(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getUserTokenBalance(address,address)"(
      user: string,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gracePeriodLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "gracePeriodLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hasVotingPeriodExpired(
      startingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasVotingPeriodExpired(uint256)"(
      startingPeriod: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    internalTransfer(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "internalTransfer(address,address,uint256)"(
      to: string,
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    makeSushiDeposit(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "makeSushiDeposit(uint256)"(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    makeXSushiDeposit(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "makeXSushiDeposit(uint256)"(
      tributeOffered: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    memberAddressByDelegateKey(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "memberAddressByDelegateKey(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    members(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "members(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    periodDuration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "periodDuration()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    processGuildKickProposal(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "processGuildKickProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    processProposal(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "processProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    processWhitelistProposal(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "processWhitelistProposal(uint256)"(
      proposalIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    processingReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "processingReward()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposalCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "proposalCount()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proposalDeposit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "proposalDeposit()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposalQueue(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proposalQueue(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proposals(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposedToKick(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proposedToKick(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proposedToWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proposedToWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ragekick(
      memberToKick: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "ragekick(address)"(
      memberToKick: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ragequit(
      sharesToBurn: BigNumberish,
      lootToBurn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "ragequit(uint256,uint256)"(
      sharesToBurn: BigNumberish,
      lootToBurn: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sponsorProposal(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "sponsorProposal(uint256)"(
      proposalId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    submitGuildKickProposal(
      memberToKick: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "submitGuildKickProposal(address,string)"(
      memberToKick: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    submitProposal(
      applicant: string,
      sharesRequested: BigNumberish,
      lootRequested: BigNumberish,
      tributeOffered: BigNumberish,
      tributeToken: string,
      paymentRequested: BigNumberish,
      paymentToken: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "submitProposal(address,uint256,uint256,uint256,address,uint256,address,string)"(
      applicant: string,
      sharesRequested: BigNumberish,
      lootRequested: BigNumberish,
      tributeOffered: BigNumberish,
      tributeToken: string,
      paymentRequested: BigNumberish,
      paymentToken: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    submitVote(
      proposalIndex: BigNumberish,
      uintVote: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "submitVote(uint256,uint8)"(
      proposalIndex: BigNumberish,
      uintVote: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    submitWhitelistProposal(
      tokenToWhitelist: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "submitWhitelistProposal(address,string)"(
      tokenToWhitelist: string,
      details: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sushiMinion(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "sushiMinion()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenWhitelist(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenWhitelist(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalGuildBankTokens(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "totalGuildBankTokens()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalLoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalLoot()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    totalShares(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totalShares()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateDelegateKey(
      newDelegateKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "updateDelegateKey(address)"(
      newDelegateKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userTokenBalances(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "userTokenBalances(address,address)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votingPeriodLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "votingPeriodLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawBalance(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "withdrawBalance(address,uint256)"(
      token: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdrawBalances(
      tokens: string[],
      amounts: BigNumberish[],
      max: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "withdrawBalances(address[],uint256[],bool)"(
      tokens: string[],
      amounts: BigNumberish[],
      max: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
